### ISSUE TITLE
Inaccurate volume data on V1 Open-Close 

### ISSUE THREAD

**Issue by cookie359** [polygon-io/issues#98] opened 2020-11-14 23:47 UTC
**URL**
https://api.polygon.io/v1/open-close/NIO/2020-11-13?apiKey=

**Result**
{
    "status": "OK",
    "from": "2020-11-13",
    "symbol": "NIO",
    "open": 51.29,
    "high": 54.2,
    "low": 40.55,
    "close": 44.56,
    "volume": 1068235096,
    "afterHours": 43.62,
    "preMarket": 49.9
}

**Expected Result**
The OHLC values seem to match other vendors, however, the volume seems to be way off (this seems to be the case for the last few days with the volume values being inflated by upto ~100%). Above is stating NIO traded over 1B shares when it actually traded ~580M.

**Screenshots**
![image](https://user-images.githubusercontent.com/26552633/99159388-b44f8f80-26d3-11eb-87ad-53921097275a.png)

**Desktop (please complete the following information):**
Tested using Postman v7.34.0

**Comment by jrbell19** [comment] 2020-11-17 22:41
This appears to be a issue related to the duplicate messages that are currently being counted for some NYSE equities. We have contacted NYSE about this and are working on a solution for the issue this week.

Apologies for the troubles.

**Comment by cookie359** [comment] 2020-11-17 22:50
OK great, thanks for the update 👍

**Comment by qrpike** [comment] 2020-11-19 21:49
This should be fixed now for this date. We are actively working on the root cause and hope to have it fixed next week with router config updates.

**Closed** 2020-11-19 21:49 UTC
Labels: bug
