### ISSUE TITLE
OTC stocks are missing from most API endpoints

### ISSUE THREAD

**Issue by bryanmorrow** [polygon-io/issues#7] opened 2020-05-07 13:50 UTC
## Overview
According to [this announcement](https://polygon.io/blog/otc-symbols-added/) in April 2018, OTC symbols should be included in the REST API. However, most OTC symbols don't seen to be available.

## Example
**[MHGU](https://www.otcmarkets.com/stock/MHGU/overview)**

https://api.polygon.io/v1/meta/symbols/MHGU/company?apiKey=XXXX
`404 Not Found`

https://api.polygon.io/v2/aggs/ticker/MHGU/range/1/minute/2020-05-06/2020-05-06?apiKey=XXXX
`{"ticker":"MHGU","status":"OK","queryCount":0,"resultsCount":0,"adjusted":true,"results":[]}`

https://api.polygon.io/v2/reference/financials/MHGU?apiKey=XXXX
`{"status":"OK","results":[]}`

**Expected Result**
That OTC stock data are available from every API endpoint in the same manner that other listed stocks are.

**Comment by clickingbuttons** [comment] 2020-05-07 17:10
Probably a duplicate of #5, but not entirely sure.

**Comment by tkenneyvt** [comment] 2020-09-23 13:29
Any update on this?  Is there a plan to add these stocks to the restful and/or websocket feeds?
I think several of these have large marketcaps... e.g. SIEGY - Siemens AG

**Comment by ilyanoskov** [comment] 2021-03-21 22:13
I second this request, it's a pity OTC symbols are excluded from the majority of endpoints

**Comment by flux77** [comment] 2022-09-24 11:03
@jrbell19
Wasn't this issue was fixed in July 2022?
https://polygon.io/blog/otc-stocks/

**Comment by clickingbuttons** [comment] 2022-09-26 14:01
Yes, we have OTC data in all our stock endpoints (see [this blog post](https://polygon.io/blog/otc-stocks/)). Closing.

**Closed by clickingbuttons** 2022-09-26 14:01 UTC
Labels: bug
