### ISSUE TITLE
QQQ Gap in Aggs

### ISSUE THREAD

**Issue by ryantjo** [polygon-io/issues#52] opened 2020-07-23 01:58 UTC
For QQQ I get zero data returned for the period 2004-11-30 - 2011-03-23 for the 1-minute aggregate

**Comment by jrbell19** [comment] 2020-07-23 18:07
It looks like this is because the tick data is missing from this period as well. We will backfill this data as soon as possible. 

Thanks for pointing this out.

**Comment by jiosec** [comment] 2020-11-21 20:21
four months passed, a simple issue like this not fixed yet?

**Comment by qrpike** [comment] 2021-01-25 19:53
Duplicate of: https://github.com/polygon-io/issues/issues/118 

Please see resolution in that ticket.

**Closed by qrpike** 2021-01-25 19:53 UTC
Labels: aggs, bug
