### ISSUE TITLE
Websocket connections disconnected every 2 hours [max]

### ISSUE THREAD

**Issue by joshlang** [polygon-io/issues#55] opened 2020-07-31 00:00 UTC
We are subscribing to trade & quote streams for ~4000 symbols via your websockets.

Every 2 hours, we're disconnected.  This requires us to reconnect, and make ~8000 HTTP GET requests for a few seconds of missing history before we are resynchronized.  It also makes us unable to make any time-sensitive trading decisions while resynchronization is occurring, since we are effectively blind.

Here's some chronology, starting last night.  All times are PST.

```
Disconnect: 10:20pm
Disconnect: 12:21am
Disconnect: 2:21am
Disconnect: 4:22am
Disconnect: 6:23am
Restart our client software: 6:45am
Disconnect: 8:23am
Restart our client software: 9:27am
Disconnect: 10:24am
Disconnect: 11:24am
Disconnect: 1:25pm
Disconnect: 3:26pm
```

The time at which we connect seems to make no difference.  So therefore, I would thinking there's something **server-side at polygon** which is restarting every 2 hours.  (Except at 11:24am, it was 1 hour instead of 2).

Hope that helps track down the problem.

**Comment by joshlang** [comment] 2020-07-31 00:15
Perhaps related: https://github.com/polygon-io/issues/issues/11

I also have tried a keep-alive message, to no avail.

**Comment by jrbell19** [comment] 2020-07-31 14:41
Thanks for this. We are aware of the issue and are actively working to resolve it. I will be sure to keep you posted on our progress. 

For now I'd recommend implementing some logic to detect the disconnect then automatically reconnect. Apologies for the inconvenience.

**Comment by tkenneyvt** [comment] 2020-08-12 13:13
Any news on this?  Its a major issue for me.   I'm only looking at AM (1 minute aggregates) and it does the same thing.

**Comment by FreeGoldRush** [comment] 2020-08-17 16:47
This continues to be a problem.  The last update from jrbell19 was 17 days ago.  What have you discovered about why this is happening?

Thank you

**Comment by degree73** [comment] 2020-08-17 17:06
@jrbell19 I agree, an update would be nice.

**Comment by joshlang** [comment] 2020-08-25 13:43
Polygon support at it's finest :/

**Comment by jrbell19** [comment] 2020-08-25 14:53
We don't yet have a concrete ETA for a fix, but we are heading up to the datacenter next weekend to troubleshoot the issue within the cage, as well as upgrade some of the equipment. 

We really appreciate your patience with us on this.

**Comment by joshlang** [comment] 2020-09-10 00:21
I've cancelled my subscription

Please reach out if you fix it

**Comment by thejeed** [comment] 2020-09-10 05:43
I've got a comparable problem - subscribing to just two symbols, I'm getting disconnects after varying amounts of time, mostly between 20 and 50 minutes of connection. Server buffer ist empty, other data streams of the system show now issues.

**Comment by degree73** [comment] 2020-09-17 18:16
@jrbell19, Do you have an update for us on this? Any progress?

**Comment by jrbell19** [comment] 2020-09-17 18:44
No fix yet. We will be upgrading the infrastructure this weekend though. We are anticipating that this will free up some bandwidth to prevent the disconnects. 

Apologies this has taken so long. It has proven more complex than we originally thought.

**Comment by degree73** [comment] 2020-09-18 16:15
@jrbell19, will you be running live on the new infrastructure on Monday? So *very* best case, it would be "fixed" Monday?

**Comment by nerka-kurt** [comment] 2020-09-25 03:39
Seeing the same issue with 1000 symbols for 1 second aggregate. Getting disconnected randomly between 5 minutes to 4 hours. Wondering how their top customers, like Google and Alpaca, handling this issue.

**Comment by degree73** [comment] 2020-10-14 17:25
@jrbell19, it's been almost a month since the last update. Do you feel you are any closer to solving this?

**Comment by jrbell19** [comment] 2020-10-26 17:48
This should be fixed now. Can you confirm? @degree73 @joshlang

**Comment by nerka-kurt** [comment] 2020-10-26 19:06
Yes. It’s fixed. That’s awesome. Great job! This was definitely not an easy task.

**Comment by degree73** [comment] 2020-10-26 20:49
@jrbell19, I can confirm that I did NOT have this issue today. So after 1 day in, things are looking good!

**Closed** 2021-01-24 18:44 UTC
Labels: bug, wip
