### ISSUE TITLE
Inconsistent API results

### ISSUE THREAD

**Issue by brycelund** [polygon-io/issues#94] opened 2020-11-02 17:43 UTC
**URL**
https://api.polygon.io/v2/aggs/ticker/SPY/range/1/hour/2020-05-15/2020-10-15?limit=60000&apiKey=XXXX

**Result**
Every time I submit the request, I get a different result back.

Attached are results of 5 of the same request to the above endpoint with 2-3 seconds between each request. Every response is different. What??

**Expected Result**
I expect a consistent, understandable response from the API. If 5 months of 1 hour data is too much for one request, then I'd expect a pagination response with a predictable limit. I don't even know what it's giving me right now.

**Screenshots**
![Screen Shot 2020-11-02 at 10 36 50 AM](https://user-images.githubusercontent.com/18741882/97900209-99564600-1cf7-11eb-8333-e5f1832645cc.png)
![Screen Shot 2020-11-02 at 10 36 44 AM](https://user-images.githubusercontent.com/18741882/97900211-99564600-1cf7-11eb-8d50-e97ceb841304.png)
![Screen Shot 2020-11-02 at 10 36 37 AM](https://user-images.githubusercontent.com/18741882/97900213-99eedc80-1cf7-11eb-9ec3-67bb16b8dec9.png)
![Screen Shot 2020-11-02 at 10 36 58 AM](https://user-images.githubusercontent.com/18741882/97900208-98bdaf80-1cf7-11eb-8bab-43d9d50ccb47.png)
![Screen Shot 2020-11-02 at 10 36 28 AM](https://user-images.githubusercontent.com/18741882/97900206-978c8280-1cf7-11eb-8e9e-fa3d4b2b2c82.png)

**Comment by clickingbuttons** [comment] 2020-11-04 17:18
Looks like a duplicate of #68, #65, and #62.

**Comment by qrpike** [comment] 2021-01-25 19:44
This should have been solved with the release of the new aggregates API: https://polygon.io/blog/aggs-api-updates/ on Dec 4th 2020. 

Closing this, please re-open if you continue to see these issues.

**Closed by qrpike** 2021-01-25 19:44 UTC
Labels: aggs, bug
