### ISSUE TITLE
snapshot reporting double actual trade volume for some symbols

### ISSUE THREAD

**Issue by FreeGoldRush** [polygon-io/issues#61] opened 2020-08-10 20:28 UTC
**URL**

/v2/snapshot/locale/us/markets/stocks/tickers

**Result**

Volume data for some symbols is double what it should be.  Appears to be NYSE stocks.

**Expected Result**

Trade volume should be the actual trade volume and not double the actual trade volume.

**Comments**

Polygon is aware of this problem but I wanted to create a bug report here to see if anyone has a clever work around.  It's been going on for about a week and I'm unable to use the API for live trading until this is fixed.  You really can not over emphasize the importance of accurate data when trading.  Errors like this can be very costly when running the data through a trading algo.

**Comment by jrbell19** [comment] 2020-08-12 13:46
This appears to be caused by duplicate messages being broadcasted somewhere along the stream. We are investigating and working on a solution now. Apologies for the inconvenience.

**Comment by FreeGoldRush** [comment] 2020-08-12 21:01
Can you just filter out duplicates on your end as a work-around?

**Comment by FreeGoldRush** [comment] 2020-09-09 21:13
It's been four weeks since this was first reported.  When will the trade volume data be corrected?  Thanks.

**Comment by jrbell19** [comment] 2020-09-17 19:54
This should no longer be an issue. We pushed a fix and have not seen any duplicate messages since Monday. 

If you happen to see any more of this behavior please let me know and I will reopen the issue.

**Comment by jrbell19** [comment] 2020-12-03 17:30
We were able to take care of the duplicate packets flowing through the websocket channel, so the snapshot endpoints will no longer report the incorrect volume figures. 

Appreciate your patience with us on this issue. It proved much more cumbersome than originally expected.

**Closed by jrbell19** 2020-12-03 17:30 UTC
Labels: bug

**Comment by FreeGoldRush** [comment] 2020-12-03 17:44
Excellent. Thank you!

Sent from my iPhone

On Dec 3, 2020, at 12:31 PM, Jack Bell <notifications@github.com<mailto:notifications@github.com>> wrote:


We were able to take care of the duplicate packets flowing through the websocket channel, so the snapshot endpoints will no longer report the incorrect volume figures.

Appreciate your patience with us on this issue. It proved much more cumbersome than originally expected.
