### ISSUE TITLE
Q4 number of shares calculations wrong

### ISSUE THREAD

**Issue by georgewild42** [polygon-io/issues#279] opened 2023-12-26 14:47 UTC
**URL**
https://api.polygon.io/vX/reference/financials?ticker=AAPL&include_sources=true&apiKey=YOUR_API_KEY

**Result**
AAPL Q4 basic_average_shares = -48266000.0

**Expected Result**
number of shares > 0

**Screenshots**
![image](https://github.com/polygon-io/issues/assets/114286070/e974fd0e-8244-4645-b7a5-9d907ee71ade)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version 121.0 (64-bit)

**Additional context**
- When calculating Q4 income statement values, Polygon does **Q4 = FY - Q3YTD** (e.g. 15,744,231 - 15,792,497 = -48266 thousand), which makes sense for things such as revenue.
- However, for number of shares this is not the right calculation since number of shares is an average.
- I believe the correct calculation (assuming all quarters have the same number of days) is **Q4 = (4 * FY) - (3 * Q3YTD)**. (this gives 15599433 instead of -48266 thousand).
- I have seen this error in multiple tickers over multiple years. It is also calculated wrong for diluted number of shares.

Thanks

**Comment by rookbreezy** [comment] 2024-01-05 20:28
I got the same number today as well. It should never be negative, strange they don't have a check for that.

Correct me if I am wrong but shares should never be calculated either, it's always listed in the report.

Getting this right is super important because it's the basis of all per share calculations. It would be nice if Polygon also included the current shares outstanding in the API. But that's a separate feature request not a bug.

# AAPL

The current shares outstanding is listed on the first page of every report:
<img width="576" alt="aapl-current" src="https://github.com/polygon-io/issues/assets/59795195/0b5bdbd9-b02a-4503-b712-7a0fd20081b8">

And the weighted average is in the income statement, below the EPS calculations:
<img width="663" alt="aapl-average" src="https://github.com/polygon-io/issues/assets/59795195/a2e01595-fc4b-444d-ae9f-9b967817f7b4">
AAPL FY: https://www.sec.gov/Archives/edgar/data/320193/000032019323000106/aapl-20230930.htm



# Visa

Tangentially related is that Polygon does not seem to return any share numbers if there are multiple share classes, like with Visa. Might make a separate issue for that. Not sure if they should be added together or reported separately in the API. 

The API also seems to be missing EPS in these cases, that could have been used to roughly calculate the shares outstanding.

<img width="759" alt="v-current" src="https://github.com/polygon-io/issues/assets/59795195/7d4f2872-469e-45cc-bcda-342ccd49689b">
<img width="629" alt="v-basic" src="https://github.com/polygon-io/issues/assets/59795195/e63a9554-85c5-46a1-9c39-29d6e6dcec22">
<img width="627" alt="v-diluted" src="https://github.com/polygon-io/issues/assets/59795195/d397fce3-389d-4a3b-8151-21780a5650f9">

Visa FY: https://www.sec.gov/Archives/edgar/data/1403161/000140316123000099/v-20230930.htm

# Berkshire Hathaway

Here there are two classes in the same report. They should not be combined.

<img width="817" alt="brk" src="https://github.com/polygon-io/issues/assets/59795195/d33a295d-9aa4-41fd-8ca0-e143998733e6">

BRK Q3: https://www.sec.gov/Archives/edgar/data/1067983/000095017023058993/brka-20230930.htm

**Comment by georgewild42** [comment] 2024-01-05 21:14
> The current shares outstanding is listed on the first page of every report: <img alt="aapl-current" width="576" src="https://private-user-images.githubusercontent.com/59795195/294593883-0b5bdbd9-b02a-4503-b712-7a0fd20081b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODcxNTUsIm5iZiI6MTcwNDQ4Njg1NSwicGF0aCI6Ii81OTc5NTE5NS8yOTQ1OTM4ODMtMGI1YmRiZDktYjAyYS00NTAzLWI3MTItN2EwZmQyMDA4MWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIwMzQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3Yzc3ZWJmNzhjYTkwYmVlZmEzOGEzYzZhNmMwN2U4ZWQ2YjIwYmVlMDRjOGNkODMwYWMwNzRiMTQzODYzNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aw0jCu7NmNTKx01LVhezNBJrDuu870r1HsN5J3WMwM0">
>
> It would be nice if Polygon also included the current shares outstanding in the API. But that's a separate feature request not a bug.

I agree, although I'm not sure if this value will be included in the XBRL files that they use to collect data since its not in a table. Hope I'm wrong though.

> And the weighted average is in the income statement, below the EPS calculations: <img alt="aapl-average" width="663" src="https://private-user-images.githubusercontent.com/59795195/294594206-a2e01595-fc4b-444d-ae9f-9b967817f7b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODcxNTUsIm5iZiI6MTcwNDQ4Njg1NSwicGF0aCI6Ii81OTc5NTE5NS8yOTQ1OTQyMDYtYTJlMDE1OTUtZmM0Yi00NDRkLWFlOWYtOWI5Njc4MTdmN2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIwMzQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNmQ2MzQ0NTJhNjA5MjM5MmY1OTc5Yjg1ODJhNjBmYzBkNWUyYjFlOWI4MDYwYzdhOThlOGEyNGU0YTMyNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GfTt8cVKopA5Ifw7hBWPQm6h0r7TuQ68ddPuLibMRJM"> AAPL FY: https://www.sec.gov/Archives/edgar/data/320193/000032019323000106/aapl-20230930.htm
> # Visa

The weighted average is the important one, because that's what you need to calculate 'per share' values accurately.

> Correct me if I am wrong but shares should never be calculated either, it's always listed in the report.

The reason they do these calculations, is that many companies do not publish a Q4 report, only an annual report.

So to work out Q4 values, they seem to be doing the annual values minus Q1 to Q3. As I stated in the original post, this is the right thing to do for values like revenue but definitely not for the average number of shares. 

The financials API is still in an experimental state, so some problems are to be expected I suppose.

Personally I would rather do calculations like this myself, and just get the raw data from Polygon.

> Tangentially related: The API does not return ANY share numbers if there are multiple share classes, like with Visa. Might make a separate issue for that. (Not sure if they should be added together or reported separately in the API)
> 
> The API also seems to be missing EPS in these cases, that could have been used to roughly calculate the shares outstanding.
> <img alt="v-current" width="759" src="https://private-user-images.githubusercontent.com/59795195/294596386-7d4f2872-469e-45cc-bcda-342ccd49689b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODcxNTUsIm5iZiI6MTcwNDQ4Njg1NSwicGF0aCI6Ii81OTc5NTE5NS8yOTQ1OTYzODYtN2Q0ZjI4NzItNDY5ZS00NWNjLWJjZGEtMzQyY2NkNDk2ODliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIwMzQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZWZjMzZiZDFkNmE0MjhiMzc0OGI3NDdiNGMyMjYyMDQxOTg1Y2VhYjFhMzljOWY2Y2FhN2VlYTY2ZjA1MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QfaD0nMPjznrxSamAKpDgqDHYcQg5meYeP0W6DK88Bw"> <img alt="v-basic" width="629" src="https://private-user-images.githubusercontent.com/59795195/294596153-e63a9554-85c5-46a1-9c39-29d6e6dcec22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODcxNTUsIm5iZiI6MTcwNDQ4Njg1NSwicGF0aCI6Ii81OTc5NTE5NS8yOTQ1OTYxNTMtZTYzYTk1NTQtODVjNS00NmExLTljMzktMjlkNmU2ZGNlYzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIwMzQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZGU3OGYwMTY4OTZhNjgzZjA5ZWI2ZGY4YTUzMmYzNmI4NGYwMmQ3NWJkMTE4YWJhYjJhMTIzMzdmODkxNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k0Ib51-p8IoxOit9QcUdoeDyzNbjECT8Cv_N2WeT0vQ"> <img alt="v-diluted" width="627" src="https://private-user-images.githubusercontent.com/59795195/294596163-d397fce3-389d-4a3b-8151-21780a5650f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODcxNTUsIm5iZiI6MTcwNDQ4Njg1NSwicGF0aCI6Ii81OTc5NTE5NS8yOTQ1OTYxNjMtZDM5N2ZjZTMtMzg5ZC00YTNiLTgxNTEtMjE3ODBhNTY1MGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIwMzQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMGUzYTdkZGUyM2RjZTQ4M2ZmMWYzZDk4OGVhMTM0NjhkODM5YjU5ZWRiOGNkMGU2ZTlhOGE1OGE3OWQ0ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zcWep1nyWGEplhWahhN6BXz_NrVB_qI3sFtHQK-ED8g">
> 
> Visa FY: https://www.sec.gov/Archives/edgar/data/1403161/000140316123000099/v-20230930.htm
> # Berkshire Hathaway
> 
> Here there are two classes in the same report. They should not be combined.
> <img alt="brk" width="817" src="https://private-user-images.githubusercontent.com/59795195/294597580-d33a295d-9aa4-41fd-8ca0-e143998733e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODcxNTUsIm5iZiI6MTcwNDQ4Njg1NSwicGF0aCI6Ii81OTc5NTE5NS8yOTQ1OTc1ODAtZDMzYTI5NWQtOWFhNC00MWZkLThjYTAtZTE0Mzk5ODczM2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIwMzQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZDlmMjUyMzgwOWJlMTVlNDA0M2EzZmI1ODgwZDkxYjQ3MWM0YWIwZGY1YzM1OGI5NjBhNzU1ZGY3Y2VlZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J_3maLa3-IhyuDOQ3JztvnTzXvvCm46DeYS4xk0DEsg">
> 
> BRK Q3: https://www.sec.gov/Archives/edgar/data/1067983/000095017023058993/brka-20230930.htm

Yes it seems you are right. I would raise it as a separate issue, as you suggested.

They will have to figure out how to match each value to the right ticker, which doesn't sound fun.

Thanks for bringing more attention to these issues.

**Comment by rookbreezy** [comment] 2024-01-05 21:33
# Implied Q

> The reason they do these calculations, is that many companies do not publish a Q4 report, only an annual report.

Just to be totally clear on this. The entire Balance Sheet and the current shares outstanding are point-in-time reported numbers. They do not need to be calculated in an implied Q4. 

For the Income Statement you need to calculate the Q4.

And for the Cash Flow Statement you actually need to imply the Q2, Q3, and Q4. As very often only the Q1 is reported as three months ended.

# XBRL

>  I'm not sure if this value will be included in the XBRL

It is. Here is the XBRL on Visa:

Basic Class A:
<img width="825" alt="basic-a" src="https://github.com/polygon-io/issues/assets/59795195/fe8cbeca-14e1-4882-933a-569c7b1f3cb2">

Basic Class B:
<img width="827" alt="basic-b" src="https://github.com/polygon-io/issues/assets/59795195/54c55f8c-1633-4b98-85cd-60e2e3fbe166">

**Comment by georgewild42** [comment] 2024-01-06 11:22
> Just to be totally clear on this. The entire Balance Sheet and the current shares outstanding are point-in-time reported numbers. They do not need to be calculated in an implied Q4.
> 
> For the Income Statement you need to calculate the Q4.
> 
> And for the Cash Flow Statement you actually need to imply the Q2, Q3, and Q4. As very often only the Q1 is reported as three months ended.

Yep, you're absolutely right.

> # XBRL
> 
> > I'm not sure if this value will be included in the XBRL files ... since its not in a table.
> 
> The current shares yes, a lot of data is in XBRL, even outside of tables.

Ah, good. Hopefully they can add it to the API.

**Comment by AHangstefer** [comment] 2024-01-23 20:07
Hi! Thanks for reaching out. We have a ticket open for this issue and hopefully it will be investigated and corrected soon. Please let me know if there's anything else I can help you with!

**Closed by AHangstefer** 2024-01-23 20:07 UTC
Labels: bug

**Comment by rookbreezy** [comment] 2024-01-23 20:12
@AHangstefer Why did you close the issue? I am still seeing the negative number in the API.

<img width="762" alt="shares" src="https://github.com/polygon-io/issues/assets/59795195/03dd996b-1ff7-4d51-b625-0f15955d3f83">
